version: "3.3"

services:
  portfolio:
    container_name: portfolio-app
    image: miguelan/portfolio:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: unless-stopped
